// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrxnbwdppoendplvwgaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyeG5id2RwcG9lbmRwbHZ3Z2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MzM5MjQsImV4cCI6MjA3NDQwOTkyNH0.Gpo4AboII7l3JFEOWamf_WbA1mHKNWZNpzP-FsOBXJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});